import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUI } from "./NextUI";
import { ChakraProvider } from "@chakra-ui/react";
import HomeLayout from "@/components/ui/layouts/HomeLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUI>
          <ChakraProvider>
            <HomeLayout>{children}</HomeLayout>
          </ChakraProvider>
        </NextUI>
      </body>
    </html>
  );
}
