import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import HomeWrapper from "@/components/ui/HomeWrapper";
import { NextUI } from "@/components/layouts/NextUI";
import { ChakraProvider } from "@chakra-ui/react";
import ThemeProvider from "@/context/Theme";
import AuthDialogProvider from "@/context/AuthDialog";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "LearnTok",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("min-h-screen font-sans antialiased", fontSans.variable)}
      >
        <ThemeProvider>
          <NextUI>
            <ChakraProvider>
              <AuthDialogProvider>
                <HomeWrapper>{children}</HomeWrapper>
              </AuthDialogProvider>
            </ChakraProvider>
          </NextUI>
        </ThemeProvider>
      </body>
    </html>
  );
}
